DROP TABLE IF EXISTS users;
CREATE TABLE users(
                      id             INT AUTO_INCREMENT NOT NULL,
                      tgId           BIGINT,
                      nameFromTg     VARCHAR(255) DEFAULT '',
                      userName       VARCHAR(255) DEFAULT '',
                      timesChosen    INT DEFAULT 0,
                      msgSaved       INT DEFAULT 0,
                      time1          BOOL DEFAULT 0,
                      time2          BOOL DEFAULT 0,
                      time3          BOOL DEFAULT 0,
                      time4          BOOL DEFAULT 0,
                      time5          BOOL DEFAULT 0,
                      time6          BOOL DEFAULT 0,
                      time7          BOOL DEFAULT 0,
                      time8          BOOL DEFAULT 0,
                      time9          BOOL DEFAULT 0,
                      time10         BOOL DEFAULT 0,
                      time11         BOOL DEFAULT 0,
                      time12         BOOL DEFAULT 0,
                      time13         BOOL DEFAULT 0,
                      time14         BOOL DEFAULT 0,
                      time15         BOOL DEFAULT 0,
                      time16         BOOL DEFAULT 0,
                      time17         BOOL DEFAULT 0,
                      time18         BOOL DEFAULT 0,
                      time19         BOOL DEFAULT 0,
                      time20         BOOL DEFAULT 0,
                      time21         BOOL DEFAULT 0,
                      time22         BOOL DEFAULT 0,
                      time23         BOOL DEFAULT 0,
                      time24         BOOL DEFAULT 0,
                      msg1           TEXT(50000),
                      msg2           TEXT(50000),
                      msg3           TEXT(50000),
                      msg4           TEXT(50000),
                      msg5           TEXT(50000),
                      msg6           TEXT(50000),
                      msg7           TEXT(50000),
                      msg8           TEXT(50000),
                      msg9           TEXT(50000),
                      msg10          TEXT(50000),
                      msg11          TEXT(50000),
                      msg12          TEXT(50000),
                      msg13          TEXT(50000),
                      msg14          TEXT(50000),
                      msg15          TEXT(50000),
                      msg16          TEXT(50000),
                      msg17          TEXT(50000),
                      msg18          TEXT(50000),
                      msg19          TEXT(50000),
                      msg20          TEXT(50000),
                      msg21          TEXT(50000),
                      msg22          TEXT(50000),
                      msg23          TEXT(50000),
                      msg24          TEXT(50000),
                      msg25          TEXT(50000),
                      msg26          TEXT(50000),
                      msg27          TEXT(50000),
                      msg28          TEXT(50000),
                      msg29          TEXT(50000),
                      msg30          TEXT(50000),
                      msg31          TEXT(50000),
                      msg32          TEXT(50000),
                      msg33          TEXT(50000),
                      msg34          TEXT(50000),
                      msg35          TEXT(50000),

                      PRIMARY KEY (`id`)
);
